### ISSUE TITLE
Fails to build on macos

### ISSUE THREAD

**Issue by ober** [justmiles/go-markdown2confluence#1]
make
env GOOS=darwin  GOARCH=amd64 go build -ldflags '-X "main.Version=2.1.0 (df35ce4ed2 2bdc968f29 61f7c00e23 758006882e - 2019-06-27 14:45)"' -o build/2.1.0/markdown2confluence-2.1.0-darwin-amd64
# github.com/justmiles/go-markdown2confluence/markdown2confluence
markdown2confluence/MarkdownFile.go:74:11: content.Ancestors undefined (type confluence.Content has no field or method Ancestors)
note: module requires Go 1.12make: *** [build] Error 2

**Comment by justmiles** [comment]
Thanks for catching this. Forgot to push go.mod changes!
