### ISSUE TITLE
Image upload capability needed

### ISSUE THREAD

**Issue by Hotpirsch** [justmiles/go-markdown2confluence#10]
Unfortunately it is not possible to upload markdown with image references:

Error creating page: Error parsing xhtml: Unexpected close tag </p>; expected </img>

**Comment by justmiles** [comment]
I've switched the backend library that parses markdown to [Goldmark](https://github.com/yuin/goldmark) and we can now list images. This doesn't yet support uploading local files to Confluence, though. Leaving this open until then.

**Comment by justmiles** [comment]
This is published in [v3.1.1](https://github.com/justmiles/go-markdown2confluence/releases/tag/v3.1.1)

**Comment by chrinder** [comment]
@justmiles This tool is great!  Saving me some time moving a small Azure DevOps wiki to Confluence.  However, it's not moving the images.  It looks like that was a new feature just added. Does this currently support uploading images referenced in the .md file to confluence?  Thanks!

**Comment by justmiles** [comment]
Yes, I've had success with it from a Linux machine. It's using golang's file library so it should work on other platforms as well. I didn't have an issue with one project and while I haven't verified it yet, I think it's choking on images with spaces in the names or file path. Are there spaces in your file name or path?

**Comment by chrinder** [comment]
Thanks for quick reply.  I'm on Mac.  I ran with --debug and didn't see any error messages.  Also I didn't see any "LOCAL IMAGE FOUND" debug messages.  I see in confluence the image tag and path to the source is identical to the path in the .md file.

`<img src="/.attachments/image-f8a682d0-a5a8-4820-ab69-46f18d3fee47.png" alt="image.png" />`

My images are stored in an invisible .attachments folder.

```
   - .attachments (all file attachments are stored here)
   - DotNet-Development-Wiki (directory for other .md wiki files)
      - Onboarding.md (has references to images in top level .attachments directory)
      - Onboarding (directory for onboarding pages)
    - DotNet-Developmnet-Wiki.md
```

**Comment by justmiles** [comment]
Could you try it in this markdown format:

```
![img.png](.attachments/image-f8a682d0-a5a8-4820-ab69-46f18d3fee47.png)
```
Also I would expect the path you provided to look for a file at the root of your file system. Instead, remove the forward slash as I did in the example to make the location relative to where your markdown file is.

**Comment by chrinder** [comment]
Thank you!! That was it.  I copied/pasted incorrectly, my .md file was using the format:

`![img.png](.attachments/image-f8a682d0-a5a8-4820-ab69-46f18d3fee47.png)`

However, it was the leading slash, which I missed, that was causing it to look at root level.  Fixed that and it works.  Awesome!  Thanks again.  Certainly saved me a lot of copy/pasting.
