### ISSUE TITLE
Possible to remove pages from the wiki where they have been deleted from disk?

### ISSUE THREAD

**Issue by petemounce** [justmiles/go-markdown2confluence#14]
Confluence doesn't expose a recursive-delete to regular users (of which I am one).

I want to be able to publish from the root of my repository's `master` branch, on merge to `master`, and not need to care about pages that have been deleted being removed (or, deleted+created; i.e. moved/renamed).

I've tried to think through the conditions and implications below. Would it be possible to have markdown2confluence handle:
* page has been deleted
  * at a leaf node; delete it
  * at an intermediate node, when a page with children is deleted, the children are elevated to the position of the parent page. So I'd thought:
    * if the directory tree has been deleted - delete from the leaves upward
    * if the _page_ has been deleted but the _directory_ has not, the auto-generated-index page must remain behind but have the down-level node be removed
* page has been renamed
  * at a leaf node; rename the page (which I assume keeps its edit-history)
  * at an intermediate node - I think there's no difference between leaf and intermediate here?
    * page: rename the node
    * directory: rename the node

**Comment by justmiles** [comment]
This is a great idea and a feature I could use myself. I'm not planning on tackling this anytime soon but will happily accept PRs if someone wants to implement this.

**Comment by justmiles** [comment]
This is available in [v4.0.0-alpha-2](https://github.com/justmiles/go-markdown2confluence/releases/tag/v4.0.0-alpha-2)
