### ISSUE TITLE
Feature: set parent content via README.md

### ISSUE THREAD

**Issue by elijahgagne** [justmiles/go-markdown2confluence#17]
If the parent page does not exist, it gets created with [default content](https://github.com/justmiles/go-markdown2confluence/blob/master/lib/file.go#L214). I propose that if a `README.md` file is present in a folder, then that gets used as the parent's content (whether it is being created or not). This would align with how GitHub and many other Git services display the readme file when you browse to the root of a folder. If no readme file is present, then the existing behavior is used.

What do you think? If you like the idea, but don't think you'd be able to implement it anytime soon, I'd be happy to take a stab at it and submit a PR.

**Comment by justmiles** [comment]
This makes sense. If you're willing to tackle it I'm happy to merge a PR!

**Comment by elijahgagne** [comment]
Merged add this, thanks!
