### ISSUE TITLE
Textflow incorrect?

### ISSUE THREAD

**Issue by Skeeve** [justmiles/go-markdown2confluence#21]
If I'm not mistaken, one should keep lines in markdown files short (See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length)

Paragraphs are denoted by an empty line.

But when I upload my markdown file I see `<br />` being inserted for each line end.

Am I doing something wrong?

Source

    Im neuen XXXX sollen, unter anderem Daten von Partnern erfasst werden, wie
    z.B. Absprung Raten von deren Kunden.
    Die Daten können über verschiedene Wege, z.B. per sftp Upload auf unseren
    Server zu uns gelangen.

Generated code

    <p>Im neuen XXXX sollen, unter anderem Daten von Partnern erfasst werden, wie<br />
    z.B. Absprung Raten von deren Kunden.<br />
    Die Daten können über verschiedene Wege, z.B. per sftp Upload auf unseren<br />
    Server zu uns gelangen.</p>

The `<br />`shouldn't be there at all.

**Comment by justmiles** [comment]
Thanks @Skeeve. This fix is in [v3.1.2](https://github.com/justmiles/go-markdown2confluence/releases/tag/v3.1.2)
