### ISSUE TITLE
WithHardWraps shouldn't be used or be an option

### ISSUE THREAD

**Issue by Skeeve** [justmiles/go-markdown2confluence#22]
See #21 

https://github.com/justmiles/go-markdown2confluence/blob/24c18135f1d4d1da64e1a2e16845127a78a754a7/lib/markdown.go#L249

**Comment by Skeeve** [comment]
See Pull request #23

**Comment by justmiles** [comment]
Thanks @Skeeve. This fix is in [v3.1.2](https://github.com/justmiles/go-markdown2confluence/releases/tag/v3.1.2)
