### ISSUE TITLE
Confluence pages created are in the old style.

### ISSUE THREAD

**Issue by Rowix** [justmiles/go-markdown2confluence#29]
Hi,

I really admire the effort put into the tool!

However what I've noticed is; when pages are created they are in the old style of editor.
There is [this](https://community.atlassian.com/t5/Confluence-questions/Confluence-API-creates-pages-in-old-editor/qaq-p/1421266) which describes the fix.

Unfortunately go is not a language which I've used much and it has been months ago when i was looking into this for the first time.

downloading the source and then doing it from so i can test some tweaks is something i just can't get working....
I would have expected that calling it like this:
`go run ..\go-markdown2confluence\main.go -u '{email}' -p '{token}' -s '{space}' -e '{site}/wiki/home' -t '{title}'  README.md`
Would have worked.

but it results in:
`
Unable to upload markdown file, README.md:
        Error checking for existing page: invalid character '<' looking for beginning of value
exit status 1
`

Because i assume the fix can be done by altering the 'content struct' in content.go with something like this:

`
	// Metadata struct {
	// 	Properties struct {
	// 		Editor struct {
	// 			Key   string `json:"key,omitempty"`
	// 			Value string `json:"value,omitempty"`
	// 		} `json:"editor,omitempty"`
	// 	} `json:"properties,omitempty"`
	// } `json:"metadata,omitempty"`
`

and then updating the file.go like

	// bp.Metadata.Properties.Editor.Key = "editor"
	// bp.Metadata.Properties.Editor.Value = "v2"

Would it be possible to add a command line parameter that can be used as --ceditor 'v2' ?

Many thanks in advance for reading this through!

**Comment by justmiles** [comment]
Hey thanks for checking this out. We haven't gotten around to fixing that unintuitive error (#7) but it rears its ugly head when there are authentication problems. Double-check your email/token/endpoint. Looking at your example, I bet it is choking on `/home` being added to the endpoint URL.

In regards to the V2 editor - sounds useful! Adding it as a flag sounds like a solid idea too. If the above note fixes your issue then I'd say keep at it and submit a PR - otherwise I can take a look.

**Comment by Rowix** [comment]
Hi, the solution to my original issue was solved by creating env variables in windows and rebooting my machine....

However what I saw is that my proposed idea works to the extend of creating a new page but then it gets messy if you try to update the existing one.

So it looks like i was close but not yet close enough....
