### ISSUE TITLE
Proposal: uses the parameter token instead of password 

### ISSUE THREAD

**Issue by x1nchen** [justmiles/go-markdown2confluence#3]
According to confluence doc https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/, we should 

1. "Generate an API Token for your Atlassian Account: https://id.atlassian.com/manage/api-tokens".
2. run the command with --password <token>

**Comment by justmiles** [comment]
Thanks for raising this. This is currently supported. You can use your Atlassian email as the `--username` and your API token as the `--password`. It isn't obvious, though, so we should make a point to elaborate that in the README.
