### ISSUE TITLE
Include Image

### ISSUE THREAD

**Issue by slohrum** [justmiles/go-markdown2confluence#30]
Hello,

we markdown2confluence appreciate "markdown2confluence" very much. As we use Github for user documentation as well there are lots of images inside. Github Markdown allows to include images.

Markdown Image Syntax: 
`![ALTTEXT] {PATH}{width="WIDTH"}`

These image links should be rendered in conflence to 
`<img src="URL" width="WIDTH" alt="ALTTEXT"/>{:width=&quot;640px&quot;}</p> `

PATH may be a relative path to the page. So the PATH has to be mapped to the image's full URL.

Thanks and Best Regards

Stefan

**Comment by justmiles** [comment]
Images are currently supported. We're using a library that strives follow the CommonMark spec. Check out [this documentation](https://spec.commonmark.org/0.29/#images) for reference. Github's markdown [is based on the CommonMark spec](https://github.github.com/gfm/#images) so it will render anything that follows the CommonMark spec. Here's an example:

```
![foo](/url "title")
```
