### ISSUE TITLE
markdown2confluence doesn't work on OSX

### ISSUE THREAD

**Issue by jenoOvchi** [justmiles/go-markdown2confluence#4]
Hi!

It's a very good tool, but i can't run it on the OSX (macOS Mojave 10.14.6).
The error is "/usr/local/bin/markdown2confluence: cannot execute binary file". On the virtual machine with Ubuntu Xenial i have no problem.

Can it be updated to work on OSX?

**Comment by justmiles** [comment]
My bad - the instructions in the README are misleading as it only shows how to download for Linux. Could you try downloading the OSX binary from the releases page and dropping it in your PATH? 

https://github.com/justmiles/go-markdown2confluence/releases

```
sudo curl -L https://github.com/justmiles/go-markdown2confluence/releases/download/v2.1.0/markdown2confluence-2.1.0-darwin-amd64
sudo chmod +x /usr/local/bin/markdown2confluence
```

**Comment by jenoOvchi** [comment]
> My bad - the instructions in the README are misleading as it only shows how to download for Linux. Could you try downloading the OSX binary from the releases page and dropping it in your PATH?
> 
> https://github.com/justmiles/go-markdown2confluence/releases
> 
> ```
> sudo curl -L https://github.com/justmiles/go-markdown2confluence/releases/download/v2.1.0/markdown2confluence-2.1.0-darwin-amd64
> sudo chmod +x /usr/local/bin/markdown2confluence
> ```

Sorry, I did not notice the OSX version in the list of release files. With it all works fine! Thank you!
