### ISSUE TITLE
Failure to upload images in pages.

### ISSUE THREAD

**Issue by bir87** [justmiles/go-markdown2confluence#42]

**Comment by bir87** [comment]
I have a folder that contain images but this is entirely excluded entirely.

**Comment by justmiles** [comment]
Could you elaborate the problem or show an example?

**Comment by justmiles** [comment]
In general this will only upload images that you're referencing in a markdown document. You can [find an example here](https://github.com/justmiles/go-markdown2confluence/issues/10#issuecomment-610090686).

**Comment by bir87** [comment]
i have a folder that contains images so i am using 
markdown2confluence -u -p -s --parent -e images-folder
it upload all the documents with .md extension but ignores all the .png extensions.

**Comment by justmiles** [comment]
I would say this is working as designed. The tool syncs markdown files, not images. If you have a markdown file that is making a reference to an image (or multiple images) it will upload them, but it won't upload a directory of unreferenced images. Instead, create or generate a markdown file that references the images and have this tool sync that document.

**Comment by bir87** [comment]
got it.

**Comment by bir87** [comment]
got it.
