### ISSUE TITLE
Error updating content: Version must be incremented on update. Current version is: 5

### ISSUE THREAD

**Issue by bir87** [justmiles/go-markdown2confluence#43]
why do i keep getting this error,if i am uploading the file for the first time.
If i have same file named "index.md" in multiple dirs will it cause this error?

**Comment by justmiles** [comment]
Yes, the same filename across multiple directories will cause this error. Until we implement a state management solution this will persist.

See [similar comment here](https://github.com/justmiles/go-markdown2confluence/issues/25#issuecomment-691544236).
