### ISSUE TITLE
"Unknown flag: --comment"

### ISSUE THREAD

**Issue by sanscontext** [justmiles/go-markdown2confluence#51]
Howdy, working through a large import and I'd love to use the comment flag. However, I'm seeing `unknown flag: --comment` and `unknown shorthand flag: 'c' in -c` when I try to use it. It also doesn't appear in the `--help text`.  

This is 3.3.1, so wondering if [this commit](https://github.com/justmiles/go-markdown2confluence/commit/239cb831b168d5b8fe0dda35c0154a77e427b662) got missed?

**Comment by justmiles** [comment]
Good catch! I never released [v3.3.2](https://github.com/justmiles/go-markdown2confluence/releases/tag/v3.3.2). It's pushed now, though.
