### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hqzqaq** [justmiles/go-markdown2confluence#57]
![image](https://user-images.githubusercontent.com/51304606/201453721-410f71fb-a673-4ef1-9717-f6c851d4c92b.png)
Why?

**Comment by justmiles** [comment]
Excellent question. A little more context could help, though.

**Comment by hqzqaq** [comment]
My system is win10，I downloaded markdown2confluence.exe.
When I execute this command on the console：
`markdown2confluence.exe -s 'test' -u 'myusername' -p 'mypassword' -e 'http://192.168.137.2:8090' -t 'test' test.md`
An error has occurred：
**panic: runtime error: invalid memory address or nil pointer dereference**

**Comment by hqzqaq** [comment]
I use Docker to deploy influence,it version is atlassian/confluence-server: 7.7.3-jdk8

**Comment by justmiles** [comment]
Thanks, that's helpful. I've only used this against Atlassian Cloud. I didn't even realize there was a public image available for the self-hosted Confluence. Does it require a license to start? If it doesn't, I might look into it.

Otherwise it would be good for someone in the community that uses a self-hosted instances to troubleshoot this.

**Comment by hqzqaq** [comment]
yes，it need a license
![](https://gis-visualization.oss-cn-beijing.aliyuncs.com/typoraImg/license.png)
and I get a license to enter confluence.
**Interestingly, the linux version is normal.**
Whether in my virtual machine or wsl2.
It seems that only the Windows version has this problem.

**Comment by vinaysrinivasan8232** [comment]
Hi Miles,

I also faced the same issue, but might have found the issue.
While executing your code in MacOS for confluence DC with debug mode I could see that while executing the GET API there is a space between the "Base URL" i.e technology-wiki and "/rest/api/content?...." which might be causing the receive a nil pointer.

DEBU[0000] GET https://technology-wiki /rest/api/content?limit=1&spaceKey=TGM%C2%A0&title=%E2%80%98Home%E2%80%99%C2%A0&type=page  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12af5d8]

goroutine 1 [running]:
github.com/justmiles/go-confluence.(*Client).request(0xc00025e040, 0x1507586, 0x3, 0x150e78f, 0x11, 0xc0000e0400, 0x47, 0x0, 0x0, 0x0, ...)
	/home/justmiles/go/pkg/mod/github.com/justmiles/go-confluence@v0.0.0-20200317030333-268fb6ceafbd/client.go:52 +0x478
github.com/justmiles/go-confluence.(*Client).GetContent(0xc00025e040, 0xc000110180, 0x1511fbe, 0x18, 0xc00033f598, 0x1, 0x1)
	/home/justmiles/go/pkg/mod/github.com/justmiles/go-confluence@v0.0.0-20200317030333-268fb6ceafbd/content.go:23 +0x10c
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestor(0xc00033fb98, 0x180ffc0, 0xc00025e040, 0x0, 0x0, 0x7ff7bfeffc0c, 0xc, 0xc00033f9a0, 0x1063de0, 0xc00033f9e8, ...)
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/file.go:167 +0x145
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestors(0xc00033fb98, 0x180ffc0, 0x180ffc0, 0xc0001b17d0, 0xc0000ba110, 0xc0000a7890)
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/file.go:140 +0xab
github.com/justmiles/go-markdown2confluence/lib.(*Markdown2Confluence).Run(0x180ffc0, 0x0, 0x0, 0x0)
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/markdown.go:248 +0x415
github.com/justmiles/go-markdown2confluence/cmd.glob..func1(0x18091a0, 0xc0001100c0, 0x1, 0xc)
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/cmd/root.go:46 +0x10d
github.com/spf13/cobra.(*Command).execute(0x18091a0, 0xc00009ab70, 0xc, 0xc, 0x18091a0, 0xc00009ab70)
	/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18091a0, 0xc00008c000, 0xc00005e748, 0x18105e0)
	/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/justmiles/go-markdown2confluence/cmd.Execute(0x15bf89c, 0x5)
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/cmd/root.go:63 +0x8f
main.main()
	/home/justmiles/workspaces/justmiles/go-markdown2confluence/main.go:11 +0x39

Please correct me if Im wrong here

**Comment by justmiles** [comment]
closing this as stale until someone with a self-hosted instance is willing to troubleshoot.
