### ISSUE TITLE
Handle invalid URLs

### ISSUE THREAD

**Issue by vinaysrinivasan8232** [justmiles/go-markdown2confluence#59]
Hi Miles,

I also faced the same issue, but might have found the issue.
While executing your code in MacOS for confluence DC with debug mode I could see that while executing the GET API there is a space between the "Base URL" i.e technology-wiki and "/rest/api/content?...." which might be causing the receive a nil pointer.

DEBU[0000] GET [https://technology-wiki /rest/api/content?limit=1&spaceKey=TGM%C2%A0&title=%E2%80%98Home%E2%80%99%C2%A0&type=page](https://technology-wiki%20/rest/api/content?limit=1&spaceKey=TGM%C2%A0&title=%E2%80%98Home%E2%80%99%C2%A0&type=page)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12af5d8]

goroutine 1 [running]:
github.com/justmiles/go-confluence.(*Client).request(0xc00025e040, 0x1507586, 0x3, 0x150e78f, 0x11, 0xc0000e0400, 0x47, 0x0, 0x0, 0x0, ...)
/home/justmiles/go/pkg/mod/github.com/justmiles/[go-confluence@v0.0.0-20200317030333-268fb6ceafbd](mailto:go-confluence@v0.0.0-20200317030333-268fb6ceafbd)/client.go:52 +0x478
github.com/justmiles/go-confluence.(*Client).GetContent(0xc00025e040, 0xc000110180, 0x1511fbe, 0x18, 0xc00033f598, 0x1, 0x1)
/home/justmiles/go/pkg/mod/github.com/justmiles/[go-confluence@v0.0.0-20200317030333-268fb6ceafbd](mailto:go-confluence@v0.0.0-20200317030333-268fb6ceafbd)/content.go:23 +0x10c
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestor(0xc00033fb98, 0x180ffc0, 0xc00025e040, 0x0, 0x0, 0x7ff7bfeffc0c, 0xc, 0xc00033f9a0, 0x1063de0, 0xc00033f9e8, ...)
/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/file.go:167 +0x145
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestors(0xc00033fb98, 0x180ffc0, 0x180ffc0, 0xc0001b17d0, 0xc0000ba110, 0xc0000a7890)
/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/file.go:140 +0xab
github.com/justmiles/go-markdown2confluence/lib.(*Markdown2Confluence).Run(0x180ffc0, 0x0, 0x0, 0x0)
/home/justmiles/workspaces/justmiles/go-markdown2confluence/lib/markdown.go:248 +0x415
github.com/justmiles/go-markdown2confluence/cmd.glob..func1(0x18091a0, 0xc0001100c0, 0x1, 0xc)
/home/justmiles/workspaces/justmiles/go-markdown2confluence/cmd/root.go:46 +0x10d
github.com/spf13/cobra.(*Command).execute(0x18091a0, 0xc00009ab70, 0xc, 0xc, 0x18091a0, 0xc00009ab70)
/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18091a0, 0xc00008c000, 0xc00005e748, 0x18105e0)
/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
/home/justmiles/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/justmiles/go-markdown2confluence/cmd.Execute(0x15bf89c, 0x5)
/home/justmiles/workspaces/justmiles/go-markdown2confluence/cmd/root.go:63 +0x8f
main.main()
/home/justmiles/workspaces/justmiles/go-markdown2confluence/main.go:11 +0x39

Please correct me if Im wrong here

**Comment by justmiles** [comment]
I suspect the passed URL included a space. I'll add this to the validation check.

**Comment by justmiles** [comment]
Fixed in [v4.0.0-alpha-2](https://github.com/justmiles/go-markdown2confluence/releases/tag/v4.0.0-alpha-2)
