### ISSUE TITLE
Docker hub image was last updated 2 years ago

### ISSUE THREAD

**Issue by lebergarrett** [justmiles/go-markdown2confluence#62]
![image](https://user-images.githubusercontent.com/20349484/214892084-a8e344bc-7e32-46b3-b841-a2524983e11c.png)

Maybe consider a simple github action to automatically build and push this image to dockerhub on commits to master?

**Comment by justmiles** [comment]
Good call. Added this to Drone: https://drone.justmiles.io/justmiles/go-markdown2confluence
