### ISSUE TITLE
Adding page with the same title breaks confluence page structure

### ISSUE THREAD

**Issue by Trandel** [justmiles/go-markdown2confluence#63]
Firstly I would like to say this is a great software and works perfectly saving the md files to confluence. 

Unfortunately the way we are trying to structure our docs doesn't work with it.

We have multiple git repositories which have a README.md file and we are trying to structure it like this:
(Confluence Space)/(Service Name)/(README.md file)

For example:
- Architecture/module-transfer/technical
- Architecture/module-crypt/technical

The individual services will run the following commands:
```markdown2confluence --space 'Architecture' --parent 'module-transfer' -t 'technical' ./README.md```
```markdown2confluence --space 'Architecture' --parent 'module-crypt' -t 'technical' ./README.md```

Existing behaviour: 
module-transfer saves the README.md as a page on confluence under Architecture/module-transfer/technical.
module-crypt saves the README.md as a page on confluence under Architecture/module-crypt/technical.
The page  Architecture/module-transfer/technical is being replaced by Architecture/module-crypt/technical and disappears. 

I hope it explains what is happening. I think the problem is that the parent is not being treated as part of the page and only the page titled 'technical' is fetched and updated.

The only workaround I found is to give each page a unique name.

Regards

**Comment by justmiles** [comment]
Thanks for taking the time to provide this feedback. A similar issue was opened in the past (#33). While we have an idea of what it'll take to fix it, no-one has invested the time into the solution. It boils down to having to persist state somehow. Right now we're matching local files to remote pages based on the page name and confluence space combo. If we can store, at minimum, a key/value pair for the local file name and the remote page id then we can create multiple Confluence documents with the same name. Until then, they have to have a unique name.

**Comment by johnhart-s1** [comment]
> Right now we're matching local files to remote pages based on the page name and confluence space combo.

If we were to instead tweak the matching process to use `{confluence space, parent title, page title}` would that eliminate the need for persistent state?

**Comment by justmiles** [comment]
Yeah, great idea. There's also the concept of ancestors, which is the full tree up to the document (although I don't think ancestors are ordered so we'd have to figure that out).

I think if you _started_ with listing all of the Confluence pages and then built what would effectively be the local path you could then diff that with what's actually on the filesystem and upload from there. Right now it's the opposite in that it looks at each file first and tries to determine where in Confluence it should go.

**Comment by justmiles** [comment]
I'm currently working refactoring this tool a bit and ran into this issue. As it turns out, this is a limitation with Confluence itself. No two pages in Confluence can share the same title. It's kind of absurd, but I don't see a way around it without updating the content itself on behalf of the user - and that seems wrong.

Here's an interesting discussion on the topic:

https://community.atlassian.com/t5/Confluence-questions/Create-same-name-pages-within-a-space/qaq-p/1216332

I'm going to close this issue for now but if a viable solution comes up we'll re-open.
