### ISSUE TITLE
handle error response and fail fast

### ISSUE THREAD

**Issue by grexe** [justmiles/go-markdown2confluence#7]
currently, when the login fails for some reason, it seems the MarkDown parser is still called and consequently returns a followup error message because it cannot parse the real error response:
```
Unable to upload markdown file, test.md:
	Error checking for existing page: invalid character '<' looking for beginning of value
```
The real error is printed first, but not handled and the program tries to continue:
```
RRO[0000] Unable to unmarshal API response. Received: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>401</status-code><message>Request rejected because issuer is either not authorized or not authorized to impersonate</message></status>'
```
The way the error is handled is a bit misleading and not very intuitive, as it hides the root cause and it looks as if the file contained a markup error.

**Comment by bosborne** [comment]
Seeing the same error, I think it's because my Confluence wiki won't accept user/pass, it only accepts logins using an API token.

**Comment by bosborne** [comment]
Works!

**Comment by bosborne** [comment]
Minor note: if CONFLUENCE_ENDPOINT has a trailing '/' it does not work, had to remove that.

**Comment by finchr** [comment]
> Minor note: if CONFLUENCE_ENDPOINT has a trailing '/' it does not work, had to remove that.

Thanks! This solved it for me.
